### ISSUE TITLE
有个小问题诶.

### ISSUE THREAD

**Issue by sm9i** [AndyJennifer/SimpleEyes#3]
我在 学习的过过程中..有几个小问题,,我还是新手,,可能有的问题幼稚..别笑....

1. VideoLandingFragment 这个视频播放页面 会在某些手机 VideoView  不会全屏....百度的教程要 重写onMeasure 方法,..
2. InterceptVerticalViewPager  的拦截事件 为什么要写在 ACTION_MOVE  里面 我调试输出  那里面的东西会运行好几次... 
3 .

https://github.com/AndyJennifer/SimpleEyes/blob/master/app/src/main/java/com/jennifer/andy/simpleeyes/ui/splash/VideoLandingFragment.kt#L71  这里为什么要这样写...这样写 我的goMainActivity 会运行好几次......  我现在初步办法是 写在  onPageSelected  判断position =4

**Comment by AndyJennifer** [comment]
@sm9i 你好，sm9i同学。这里非常感谢你对项目的关注与提出的问题。因为前期为了赶功能，所以代码写的比较糙一点，我自己也没有实际的去检查代码是否合理。针对与你提出的1.2.3个问题。我会尽快的修复。如果你对这个项目也非常感兴趣，也期待与你的合作。这里再次感谢你对项目的支持与关心。比心 。❤

**Comment by sm9i** [comment]
加油呀
